version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: recipes_app
      MYSQL_USER: root
      MYSQL_PASSWORD: 0000
      MYSQL_ROOT_PASSWORD: 0000
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
